# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

- The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
- The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).


In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
import torch


rand_t = torch.rand(size=(7, 7))

rand_t

tensor([[0.9153, 0.0769, 0.9136, 0.6304, 0.8183, 0.2874, 0.4626],
        [0.8074, 0.7636, 0.5098, 0.6815, 0.8685, 0.1328, 0.0294],
        [0.4196, 0.5155, 0.6463, 0.0240, 0.4637, 0.7696, 0.0603],
        [0.8519, 0.6064, 0.8218, 0.7539, 0.2926, 0.6467, 0.6755],
        [0.6049, 0.7038, 0.4881, 0.8761, 0.4810, 0.8931, 0.9012],
        [0.5705, 0.2635, 0.0561, 0.9076, 0.2133, 0.7021, 0.4264],
        [0.2221, 0.1725, 0.4314, 0.1041, 0.0056, 0.8376, 0.2500]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).


In [ ]:
rand_t2 = torch.rand(size=(1, 7))
rand_t2_T = rand_t2.T

result = torch.mm(rand_t, rand_t2_T)
result

tensor([[1.7763],
        [1.6136],
        [1.0856],
        [1.6614],
        [1.6515],
        [0.8868],
        [0.5659]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:

```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```


In [ ]:
torch.manual_seed(0)

tensor_ = torch.rand(size=(7, 7))
tensor_2 = torch.rand(size=(1, 7))
tensor_2_T = tensor_2.T

result = torch.mm(tensor_, tensor_2_T)
result

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)

- If there is, set the GPU random seed to `1234`.


In [ ]:
torch.cuda.manual_seed(1234)

### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```


In [ ]:
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

print(tensor_A)
print(tensor_B)

### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:

```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```


In [ ]:
result = torch.matmul(tensor_A, tensor_B.T)

print(result)
print(result.shape)

### 8. Find the maximum and minimum values of the output of 7.


In [ ]:
max_value = torch.max(result)
min_value = torch.min(result)

print(max_value)
print(min_value)

### 9. Find the maximum and minimum index values of the output of 7.


In [ ]:
max_index = torch.argmax(result)
min_index = torch.argmin(result)

print(max_index.item())
print(min_index.item())

### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```


In [ ]:
torch.manual_seed(7)

tensor = torch.rand(1, 1, 1, 10)
squeezed_tensor = torch.squeeze(tensor)

print(tensor, tensor.shape)
print(squeezed_tensor, squeezed_tensor.shape)